version: "2.2"
services:
  blazegraph:
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - /data/${COMPOSE_PROJECT_NAME}/blazegraph-journal/:/blazegraph-data:rw
      - /data/${COMPOSE_PROJECT_NAME}/rdf-data:/datasets:rw
  metaphactory:
    volumes:
      - /data/${COMPOSE_PROJECT_NAME}/researchspace-runtime-data/:/runtime-data:rw
      - /apps
  metaphactory-dev-webhook:
    container_name: "${COMPOSE_PROJECT_NAME}-metaphactory-dev-git-webhook" 
    restart: unless-stopped
    build:
     context: ../dev-git-webhook
    environment:
     - VIRTUAL_HOST=webhook-${COMPOSE_PROJECT_NAME}.${HOST_NAME} 
     - LETSENCRYPT_HOST=webhook-${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
     - WEBHOOK_SECRET=${WEBHOOK_SECRET}
     - WEBHOOK_HOOKS_DIR=/code/hooks
     - WEBHOOK_BRANCH_LIST=develop
     - WEBHOOK_APP_DIRECTORY=performing-arts-ch
     - WEBHOOK_GIT_REPOSITORY=https://github.com/sapa/performing-arts-ch-templates.git
    volumes_from:
     - metaphactory
    volumes:
     - ../dev-git-webhook/code/:/code
    networks:
     - default
     - metaphactory_network
    depends_on:
     - metaphactory
