version: "2.2"
services:
  backup-container:
    container_name: "${COMPOSE_PROJECT_NAME}-backup-container"
    build:
      context: backup-container
    volumes:
      - /data/:/data/:rw
    networks:
      - default
    env_file:
      - /data/secrets/aws_secret.env
    environment:
      - BACKUP_NAME=${COMPOSE_PROJECT_NAME}-backup
      - BACKUP_BASE_PATH=/data/backup
      - BACKUP_RUNTIME_NAME=${COMPOSE_PROJECT_NAME}-runtime-backup
      - FOLDERS_TO_BACKUP=/data/${COMPOSE_PROJECT_NAME}/blazegraph-journal
     #FIXME: Is this really supposed to be the runtimefolder to backup? If not, consider adding a env var called APP_NAME and place on dev/prod .env and put /apps inside /data, perhaps?
     # - FOLDERS_TO_BACKUP_RUNTIME=/data/${COMPOSE_PROJECT_NAME}/researchspace-runtime-data
      - FOLDERS_TO_BACKUP_RUNTIME=/apps/performing-arts-ch/researchspace-runtime-data
      - KEEP_BACKUP_DAYS=${KEEP_BACKUP_DAYS}
      - S3_BUCKET_URL=${S3_BUCKET_URL}
      - ENDPOINT_URL=${ENDPOINT_URL}
