version: "2.2"
services:

 metaphactory:
  container_name: "${COMPOSE_PROJECT_NAME}-metaphactory"
  image: "${METAPHACTORY_IMAGE}"
  restart: unless-stopped
  environment:
     - PLATFORM_OPTS=${METAPHACTORY_OPTS}
     - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - JAVA_OPTS=-Xmx1g
     - GENERATE_METAPHACTORY_PASSWORD=${GENERATE_METAPHACTORY_PASSWORD}
     # LETSENCRYPT variables will take effect only when nginx-proxy is setup with Let's Encrypt support
     - LETSENCRYPT_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  networks:
#     - default
     - metaphactory_network
  volumes:
     - metaphactory-runtime-data:/runtime-data
  logging:
   driver: json-file
   options:
    max-size: "200k"
    max-file: "10"
 
 cron-backups:
  container_name: "${COMPOSE_PROJECT_NAME}-cron-backup"
  restart: unless-stopped
  build:
    context: ../cron-backup
  environment:
    - CRON_SCHEDULE=${BACKUP_CRON_SCHEDULE}
    - BACKUP_NAME=${COMPOSE_PROJECT_NAME}-backup
    - FOLDERS_TO_BACKUP=/data /config
    - NUMBER_OF_BACKUPS_TO_KEEP=${BACKUP_RETENTION_NUMBER}
  volumes:
    - /backups
  volumes_from:
    - metaphactory
  depends_on:
    - metaphactory
  restart: always
  networks:
    - metaphactory_network

volumes:
  metaphactory-runtime-data:

networks:
#  default:
#    external:
#      name: nginx_proxy_network
  metaphactory_network:
