version: "2.2"
services:
  blazegraph:
    #blazegraph-overwites here
    #ports:
    # - "10214:8080"
    #environment:
    #  - JAVA_OPTS=-Xmx2g
  metaphactory:
    #metaphactory-overwites here
    ports:
    - "10214:8080"
    #environment:
    #  - JAVA_OPTS=-Xmx1g
    volumes:
      - ../../performing-arts-ch-templates:/performing-arts-ch-runtime
